[phases.setup]
nixPkgs = ['php82', 'composer', 'libmysqlclient']

[phases.install]
cmds = ['composer install --no-interaction --prefer-dist']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=${PORT}'
