[setup]
packages = ["php82", "php82Extensions.mbstring", "php82Extensions.pdo_mysql", "nginx", "composer"]

[build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "php artisan config:cache"
]

[start]
cmd = "php-fpm -y /etc/php-fpm.conf & nginx -c /etc/nginx/nginx.conf"
